### ISSUE TITLE
How to train a IBM Cloud Pak for Data Watson Discovery model with training data queries created from its API? 

### ISSUE THREAD

**Issue by shirleyow** [ibm-cloud-docs/discovery-data#8]
Managed to create the training data queries on Python but unable to train the model with the training data queries. Using a relevancy scoring range of 0 - 2, different from that of the tooling system (either 0 or 10), thus seemingly unable to train the model on the tooling interface as well. 

Would greatly appreciate help, thank you!

**Comment by fedigank5** [comment]
@shirleyow Because this is a documentation repository, you might want to instead post your issue on the [IBM Cloud Pak for Data Community](https://community.ibm.com/community/user/cloudpakfordata/home) or on the [IBM Support](https://www.ibm.com/mysupport/s/topic/0TO50000000IYkUGAW/cloud-pak-for-data?language=en_US) channels.

In the meantime, the sentence after step 3 (about relevancy scores) in this section may help you: https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-train#results

**Comment by shirleyow** [comment]
@fedigank5 I see, sure, thanks for directing me to the right channels!
